### ISSUE TITLE
Current version do not support job feature

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/Hack-SpaceVim#11]
This is because your version of vim is lower than `vim(v7.4.1325)`. 
You have to upgrade your vim to higher version with `+job` feature.

vim with `+job`(Higher Version):
![vim+job](https://cloud.githubusercontent.com/assets/12933851/25009852/bfb2b7a0-209a-11e7-9410-5c38a7e413d2.jpg)

vim with `-job`(Lower Version):
![vim-job](https://cloud.githubusercontent.com/assets/12933851/25009857/c7416dc2-209a-11e7-9dfc-03667d9dc6ca.jpg)

Thanks @unixcx

**Comment by wsdjeg** [comment]
`+job | vim: +v7.4.1325`

**Comment by Gabirel** [comment]
Oh, that's so accurate~
