### ISSUE TITLE
Here is how I enable +python and +lua and +python3 in win7

### ISSUE THREAD

**Issue by wsdjeg** [Gabirel/Hack-SpaceVim#17]
### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(C:\Program Files\vim80\gvim.exe)
version: 800
OS: Windows
[shell, shellcmdflag, shellslash]: ['C:\Windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

**Comment by Gabirel** [comment]
I can't know how although you passed health check

**Comment by Gabirel** [comment]
The right way to configure:
```viml
set pythonthreedll=python36.dll
set pythondll=python27.dll
```

It has default value. That's why I can make vim support python2 and python3 at the same time.

**Comment by wsdjeg** [comment]
it is based on the output of 
```
py -2 --version
py -3 --version
```

**Comment by Gabirel** [comment]
Summary:
```shell
py -2 --version
py -3 --version
```

Based the version of python, set default value of python support for vim.
```
set pythonthreedll=python36.dll
set pythondll=python27.dll
```
