### ISSUE TITLE
Windows: Instructions For Installing SpaceVim

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/Hack-SpaceVim#2]
Many people may confused about how to install SpaceVim on Windows.

So, I decide to write an instructions about how to install SpaceVIm on your Windows and make sure I can solve all the problems when installing.

**Comment by wsdjeg** [comment]
yeah, if your vim has no lua support, the autocomple tool is neocomplcache, it is too slow, and to install and update plugins we need job and python support.

**Comment by Gabirel** [comment]
Why python support is a necessary? Just for update plugins or so?

**Comment by wsdjeg** [comment]
yeah, and ctrlp's pymatch need python support.

**Comment by Gabirel** [comment]
Thanks

**Comment by Gabirel** [comment]
@wsdjeg I am gonna abandon full English mode of installation instructions.
My computer won't allow me to install English package. Sorry for this.

I am still gonna use Chinese instructions for English users.
