### ISSUE TITLE
python version check command fail

### ISSUE THREAD

**Issue by hotleave** [Gabirel/Hack-SpaceVim#23]
[Start to install - step 3](https://github.com/Gabirel/Hack-SpaceVim/blob/master/en_US/installation/installation-for-linux.md#start-to-install)

```
python -v
```

where `-v` means _verbose_, but `-V` means _version_. Here is part of `python --help`:

```
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
-V     : print the Python version number and exit (also --version)
```

**Comment by Gabirel** [comment]
It's my mistake. Fix later.
You should use `-V` instead
