### ISSUE TITLE
vimproc.vim Building

### ISSUE THREAD

**Issue by dedoyle** [Gabirel/Hack-SpaceVim#26]
gvim+win7+python3+lua
按照 hackspacevim 的教程安装的，改做的都做了，初次进入gvim，安装插件时，其他插件都是 installing done，但是 vimproc.vim 就显示 *vimproc.vim Building，一直都没有done。build vimproc.vim 还有其他环境要求，还是什么问题

**Comment by Gabirel** [comment]
1. win7是32位还是64位？
2. `.cache\vimfiles\repos\github.com\Shougo\vimproc.vim\lib`下的内容是什么？最好是截图看下

**Comment by ejzhang** [comment]
[https://github.com/Shougo/vimproc.vim/releases](url)

**Comment by wsdjeg** [comment]
现在build状态还会一直存在，看来需要设置一个 timeout。

________________________________
wsdjeg@outlook.com
