### ISSUE TITLE
Links before TOC

### ISSUE THREAD

**Issue by wsdjeg** [Gabirel/Hack-SpaceVim#37]
I just check the readme, the links before the toc makes me confused. the alt text is `中文文档` and `English Document`, but this link is not http://spacevim.org/documentation/ and http://spacevim.org/cn/documentation/

the resource of SpaceVim is:

1. SpaceVim's github is for developers
2. SpaceVim's website and documentation is for users
3. Hack-SpaceVim's issue is for ask question about how to hack SpaceVim
4. SpaceVim's issue is for bug report and feature requst

so how about:

[SpaceVim](https://github.com/SpaceVim/SpaceVim) | [Hack-SpaceVim 中文版](https://github.com/Gabirel/Hack-SpaceVim/blob/master/README_zh_CN.md) | [Ask question](https://github.com/Gabirel/Hack-SpaceVim/issues) | [Bug report & Feature request](https://github.com/spacevim/spacevim/issues)

**Comment by Gabirel** [comment]
Nice way to have all this embedded.

**Comment by wsdjeg** [comment]
Thanks.
