### ISSUE TITLE
tar SpaceVim-v0.3.0-plugins-Linux_x86_64-offline.tar.gz failure. any solutions?

### ISSUE THREAD

**Issue by haomeng689** [Gabirel/Hack-SpaceVim#39]
tar SpaceVim-v0.3.0-plugins-Linux_x86_64-offline.tar.gz failure. any solutions?

**Comment by wsdjeg** [comment]
spacevim  do not provide any .tar.gz package, please use official install script, or use git.

**Comment by haomeng689** [comment]
Oh, I use a remote server without Internet connection and the only operation allowed is uploading files. I have to create a portable spacevim.

**Comment by Gabirel** [comment]
Comment here: https://github.com/Gabirel/Hack-SpaceVim/issues/12#issuecomment-400877395

I will try to fix that later. Thanks for your feedback. @haomeng689

**Comment by wsdjeg** [comment]
Hi, we need to improve the step of offline installation. and all plugins in alll layers should be included, after that, people can enable every layer even if they are using spacevim without Internet connection.

**Comment by Gabirel** [comment]
Improve what? Can you be more specific?

**Comment by haomeng689** [comment]
wsdjeg's suggestions are great. I cannot wait to see the new package.

**Comment by Gabirel** [comment]
This problem results from compressing a symbolic link and extracting from it.
