### ISSUE TITLE
Good Directory Structure

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/Hack-SpaceVim#4]
I want this to have a very good, at least good, directory structure for the search or reference for users.

So, anybody could find what he wants without wasting too much time.

**Comment by Gabirel** [comment]
@wsdjeg Any suggestion?

**Comment by wsdjeg** [comment]
for a new user of spacevim, I think he want to know:

1. what is spacevim?
2. how to install spacevim?
3. how to use?
4 what is the features of spacevim?

**Comment by Gabirel** [comment]
No, I won't accept this.

This kind of structure should be called: "SpaceVim Documents", instead of `Hack SpaceVim`.

**Comment by wsdjeg** [comment]
yeah, so what do you want to write in this repo?

**Comment by Gabirel** [comment]
- Enhance the official documents
- Bigger FAQ
- Bigger instructions for SpaceVim
- Trick Techniques for SpaceVim

All above are documents which cannot easily integrated by SpaceVim

**Comment by wsdjeg** [comment]
now I think the most importent is the installation of SpaceVim.

**Comment by Gabirel** [comment]
Yeah, that's true. Hack-SpaceVim does want to include the installation.

But others?

**Comment by wsdjeg** [comment]
SpaceVim's leader guide feature and unite and denite layer.

**Comment by Gabirel** [comment]
That's a whole bunch of stuff. We are gonna talk it later.

What else?

**Comment by wsdjeg** [comment]
what is true colors, as SpaceVim use true colors by default.

how to install vim with lua python python3 support?

neovim installation.

**Comment by Gabirel** [comment]
Where's the big picture? I want a big picture right now.

**Comment by wsdjeg** [comment]
you can use same url in the readme of spacevim

**Comment by Gabirel** [comment]
Reference: https://github.com/Gabirel/Hack-SpaceVim/issues/15

**Comment by Gabirel** [comment]
Close in #15
