### ISSUE TITLE
Wrong command for installing tern in JS IDE section

### ISSUE THREAD

**Issue by Devdutt-Shenoi** [Gabirel/Hack-SpaceVim#41]
In 'en_US/IDE/JavaScript.md' the bash command used to install tern server is pretty confusing as GitHub outputs the MarkDown using the quotation shortcodes:
```markdown
> cd ~/.cache/vimfiles/repos/github.com/ternjs/tern_for_vim 
> npm install tern
```
in a single line, I have written a [PR to make use of the GitHub version of MarkDown]("https://github.com/Gabirel/Hack-SpaceVim/pull/40") to make it more clear for everyone.

**Comment by Gabirel** [comment]
Thanks for your feedback.
