### ISSUE TITLE
[Question] How to change layer options using init.vim

### ISSUE THREAD

**Issue by ViiEx** [Gabirel/Hack-SpaceVim#51]
I'm trying to configure my spacevim using `init.vim` instead of `init.toml`. I was wondering tho how can I set the layers options tho.

For example I wanted to change the `shell` position to be at the bottom instead at the top. With a little bit of digging into the source code of SpaceVim I tried the following:

```vim
call SpaceVim#layers#shell#set_variable(['terminal', 'bottom', 30, 1])
```
The above function is located at `.SpaceVim/autoload/SpaceVim/layers/shell.vim` at the line `138`

That only resulted on opening the shell at the right side instead of the bottom.

Any ideas on how to change the my shell to open the way I intend it to and how can I set layer options on `init.vim` ?

**Comment by Gabirel** [comment]
Sorry for the late reply.

## Here is the solution

```vim
call SpaceVim#layers#load('shell')

" this call function MUST STAY BELOW
" otherwise, it will get overwritten by `call SpaceVim#layers#load('shell')`
call SpaceVim#layers#load('shell',
    \ {
    \  'default_position' : 'bottom',
    \  'default_height' : 100,
    \ }
    \ )
```

<details>
<summary>Check the demo</summary>

![image](https://user-images.githubusercontent.com/12933851/172156307-62a4c880-eb5f-45a8-a058-74c08be2d919.png)

</details>

I hope this would solve your problem.
## Other

I will update your question to Hack-SpaceVim documentation. Thank you for your question.

**Comment by ViiEx** [comment]
Works perfectly thank you a lot for the quick reply!!!!
