### ISSUE TITLE
Add a new SVG with SpaceVim version

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/Hack-SpaceVim#8]
Add a new SVG with SpaceVim version for documentation.

**Comment by Gabirel** [comment]
@wsdjeg
[![spacevim-version](https://gist.githubusercontent.com/Gabirel/b71a01cce86df216abd4fd0968864942/raw/9293d3c55953e1615a134261b2885d0d683f6fcd/spacevim-0.3.0-dev.svg)](https://spacevim.org)

Is there any way to make it display what I want?

**Comment by wsdjeg** [comment]
yeah, you can make a new one in shields.io

**Comment by Gabirel** [comment]
Thanks for your help

[![spacevim-version]https://img.shields.io/badge/spacevim-v0.3.0--dev-ff69b4.svg](https://spacevim.org)
